### PR TITLE
fix: Remove erroneous inkscape attributes that make SVG invalid

### PR DESCRIPTION
**Pull request by uhle**
The SVG files for libreoffice, galculator and texmacs contain erroneous inkscape attributes that make the SVG files invalid, so they cannot be rendered by dde-launcher for instance. Simply removing these unneeded attributes fixes it.

### CODE REVIEW

**Comment by uhle** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by BLumia** [comment]
Hey thanks for the patch! Just for clarify, did you made the texmacs.svg that included in this patchset by yourself?

**Comment by uhle** [comment]
No, `texmacs.svg` has already been present in the icon theme `bloom` as you can see in the repository. While I was fixing it, I yet realized that unlike the other TeX editor icons it was missing in `bloom-classic` as well as in `Sea`. So I simply thought it would be good if it was also in the other two icon themes (similar to `texmaker.svg` and `texstudio.svg` for instance) and copied it.

**Comment by BLumia** [comment]
Thanks for clarify! So far it looks good to me. I'll pass to the related team next week :)

**Review by shule1987 — APPROVED** [review]

**Review by BLumia — APPROVED** [review]

**Pull request merged**
